global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Game Service
  - job_name: 'game-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']

  # Order Service
  - job_name: 'order-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']

  # Analytics Service
  - job_name: 'analytics-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3002']
