apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lugx-gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: buddhimaparakramage/lugx-frontend:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: API_GAME_URL
              valueFrom:
                configMapKeyRef:
                  name: lugx-gaming-config
                  key: API_GAME_URL
            - name: API_ORDER_URL
              valueFrom:
                configMapKeyRef:
                  name: lugx-gaming-config
                  key: API_ORDER_URL
            - name: API_ANALYTICS_URL
              valueFrom:
                configMapKeyRef:
                  name: lugx-gaming-config
                  key: API_ANALYTICS_URL
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lugx-gaming
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
