apiVersion: v1
kind: Secret
metadata:
  name: lugx-gaming-secrets
  namespace: lugx-gaming
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=   # base64 encoded "postgres"
  DB_PASS: cGFzc3dvcmQ=   # base64 encoded "password"
